version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update host file
          command: |
            echo 127.0.0.1 oidc-provider | sudo tee -a /etc/hosts
            cat /etc/hosts
      - run:
          name: Upgrade Nodejs
          command: |
            ./load-nvm.sh
            node -v
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: docker-compose up --build -d
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: |
          ./load-nvm.sh
          node -v
          node ./node_modules/.bin/mocha
