version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - command: |
          sudo echo '127.0.0.1 oidc-provider' >> /etc/hosts
      - checkout
      #- setup_remote_docker
      #    docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
